### ISSUE TITLE
Fails to publish: "Spawn failed"

### ISSUE THREAD

**Issue by DanLatimer** [NativeScript/nativescript-cloud#162]
When running from cli or nativescript sidekick I'm getting the same error when trying to publish ios.

```
[19-03-28 14:08:43.502] Spawn failed.
, Error: Spawn failed.
    at CloudPublishService.getiOSError (C:\Users\XXX\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:79:21)
    at CloudPublishService.<anonymous> (C:\Users\XXX\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:96:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\XXX\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:4:58)
    at <anonymous>
```

I see that [someone else is also experiencing this issue](https://stackoverflow.com/questions/55400172/spawn-failed-problem-publishing-to-apple-store/55403408#55403408) so it might be a recent release that's cause it or a recent change on apple's side. Either way the nativescript-cloud library fails to output the error that is sent from apple down.

**Comment by DanLatimer** [comment]
I've solved my problem but I still think that this explosion when trying to get the actual error needs to be fixed. I was able to figure it out without the failure log after hours of work.

You can reproduce this explosion in multiple ways but one way is by publishing a ios build but passing the app specific password with the appleId instead of the apple Id's password.

nativescript-cloud seems to attempt to format the error that it got back from apple in a nice way but explodes while doing so doing the exact opposite from the code's intentions as we don't even see the raw failure from apple. It would be far better to just show the user the raw apple error

**Comment by bhavincb** [comment]
@DanLatimer  i'm also having same issue. any workaround?

**Comment by sepccom** [comment]
same error here as well. any update?

**Comment by rebz** [comment]
Same error.

**Comment by rebz** [comment]
Update: While I have not been able to publish, I was able to get through this.

* Double check and ensure your App ID and Bundle ID match. Do a project-wide search for variations of what you think the name may be.
* Run `tns doctor` and fix any issues you may have. For me `nativescript`, `tns-core-modules, `tns-android`, and `tns-ios` were not up-to-date.
* For my project, removing and uninstalling `VueDevtools` fixed another error.
* After applying changes, delete the `platforms` folder and run `tns prepare ios --release --bundle`. Fix any warnings you may find.
* Ran into another error which was fixed by ensuring that I created my app in https://appstoreconnect.apple.com/ first. This is not noted in the documentation.

It was after going through this that I was able to get past the errors. However, I am still unable to publish.

Sidekick is stuck on asking `Password (application-specific for email@domain.com)`. No matter how many times I Verify it never gets past this step. I've tried recreating my CSR and mobileprovision file too.

Viewing the logs gives me this response after every submission.
`[19-05-24 18:09:47.989] (Info) ab.publish.shell.sendCloudMessage - No value provided`

**Comment by nlmunro** [comment]
Same :-(

**Comment by philicomus** [comment]
I'm getting the same issue intermittently just after entering the code for 2FA. Once this occurs it can be days before it seems to right itself again, so very frustrating. I don't have a MAC so can't upload my .ipa via the XCODE uploader either.

Log:

```
(Info) ab.publish.ui.sendCloudMessage - {"requestData":{"body":{"inputRequestId":"8dee2e51-dfe7-458a-8a47-5ae2994161a7","inputType":"text","message":"Please enter the 6 digit code: "},"cloudOperationId":"2f43f600-2f32-4eea-ad06-bfddce3f0539","type":"inputRequest"},"response":"618132"}
[19-06-26 20:16:34.540] (Info) ab.publish.shell.sendCloudMessage - No value provided
[19-06-26 20:16:35.248] (Info) ab.subscriptions.ui.requestUsageInfo - No value provided
[19-06-26 20:16:41.970] (Error) ab.publish.shell.publishToItunesConnect - Spawn failed.
, Error: Spawn failed.

    at CloudPublishService.getiOSError (C:\Users\phil_\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:79:21)
 
```

**Comment by nlmunro** [comment]
Mine was simply Spawn failed and turned out to be permissions in my Apple project. Yours may be different but worth double checking your user has permission for the project and the application specific password is correctly set up (this is asked for after the 2FA code).
